name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  push:
    branches:
      - main
jobs:
#   Explore-GitHub-Actions:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
#       - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#       - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#       - run: echo "The shortname of your branch is ${{ github.ref_name }}"
#       - name: Check out repository code
#         uses: actions/checkout@v4
#       - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
#       - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
#       - name: List files in the repository
#         run: |
#           ls ${{ github.workspace }}
#       - run: echo "ğŸ This job's status is ${{ job.status }}."
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: actions/github-actions-test@v1
        with:
         who-to-greet: 'Mona the Octocat'
#   test-bash:
#     runs-on: ubuntu-latest
#     defaults:
#         run:
#             working-directory: ./scripts
#     steps:
#         - name: Check out the repository to the runner
#           uses: actions/checkout@v4
#         - name: Make the script files executable
#           run: chmod +x test.sh
#         - name: Run the scripts
#           run: |
#            ./test.sh
